windmill:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Velocity controller ---------------------------------------
  windmill_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_windmill_rotor
    pid: {p: 0.25, i: 0, d: 0.0}